grails-app/domain/es/xoubin/domain/Invoice.groovy
package es.xoubin.domain

class Invoice {
	
	String reference
    Integer tipo = 0
	Integer tax	= 21
	String total
    String titular
	String payMethod
	// Quantity of invoice total taxes (total * (tax / 100))
	String totalInvoiceTaxes
	// Total of orders taxes
	String totalOrderTaxes
	String totalMinusOrderTaxes
	String totalWithTaxes
	String customer
	String nif
	String address
	Date dateInvoice
	Date dateCreated
	Date lastUpdated
    Double retention = 9
    String totalInvoiceRetention
	
	static hasMany = [invoiceOrders: InvoiceOrder]
	static belongsTo = [agent: Agent]
	
	static mapping = {		
		invoiceOrders sort: 'dateCreated', order: 'desc'
	}

    static constraints = {
		reference(blank: true, nullable: true)
        titular(blank: true, nullable: true)
		total(blank: true, nullable: true)
		payMethod(blank: true, nullable: true)
		totalInvoiceTaxes(blank: true, nullable: true)
		totalOrderTaxes(blank: true, nullable: true)
		totalMinusOrderTaxes(blank: true, nullable: true)
		totalWithTaxes(blank: true, nullable: true)
		tax(blank: true, nullable: true)
		dateInvoice(blank: true, nullable: true)
		customer (blank:true, nullable: true)
		nif (blank:true, nullable: true)
		address (blank:true, nullable: true)
        retention (blank:true, nullable: true)
        totalInvoiceRetention (blank:true, nullable: true)
    }
}

grails-app/domain/es/xoubin/domain/InvoiceOrder.groovy
package es.xoubin.domain

class InvoiceOrder {
	
	String name
	String reference
	String total
	Date dateCreated
	static belongsTo = [invoice: Invoice]
	
    static constraints = {
		name(sizeof: 5..100, blank: true)
		reference(sizeof: 5..255, blank: true, nullable: true)
		total(scale:2, blank: true, nullable: true)
	}
}

grails-app/controllers/es/xoubin/controller/InvoiceorderController.groovy
package es.xoubin.controller

import es.xoubin.domain.InvoiceOrder
import es.xoubin.domain.Invoice
import org.springframework.dao.DataIntegrityViolationException
import java.text.DecimalFormat;

class InvoiceorderController {

    def _addOrder(){
        InvoiceOrder invoiceOrder=new InvoiceOrder(params)
        invoiceOrder.invoice= Invoice.findById(params.idInvoice)
		def invoice = Invoice.findById(params.idInvoice)
		if (invoice.totalOrderTaxes==null){
			invoice.totalOrderTaxes='0'
		}
		if (invoice.totalWithTaxes==null){
			invoice.totalWithTaxes='0'
		}
        invoice.retention = Double.parseDouble(params.retention)
		def totalOrder = Double.parseDouble(params.total)
		def tax = Invoice.findById(params.idInvoice).tax
		def taxOrder = totalOrder * (tax / 100)

		invoice.totalOrderTaxes = Double.parseDouble(invoice.totalOrderTaxes) + taxOrder
        invoice.totalOrderTaxes = Double.parseDouble(invoice.totalOrderTaxes)
        invoice.totalOrderTaxes = Math.rint(Double.parseDouble(invoice.totalOrderTaxes) * 100)/100;
		invoice.totalWithTaxes = Double.parseDouble(invoice.totalWithTaxes) + totalOrder + taxOrder
        invoice.totalWithTaxes = Math.rint(Double.parseDouble(invoice.totalWithTaxes) * 100)/100;

        def ret = totalOrder * (invoice.retention / 100)
        def total = Double.parseDouble(invoice.totalWithTaxes) - ret
        if (invoice.totalInvoiceRetention==null){
            invoice.totalInvoiceRetention='0'
        }
        def doubleRetention=Double.parseDouble(invoice.totalInvoiceRetention) + ret
        invoice.totalInvoiceRetention = Math.rint(doubleRetention * 100)/100;
        invoice.totalWithTaxes = Math.rint(total * 100)/100;

		invoiceOrder.dateCreated = new Date()

        if (invoiceOrder.save(flush: true)){
            render(contentType: 'text/json') {[
                    'success': "OK",
                    'id': invoiceOrder.id,
                    'idInvoice': params.idInvoice,
                    'invoiceOrderName': invoiceOrder.name,
					'invoiceOrderReference': invoiceOrder.reference,
                    'invoiceOrderTotal': invoiceOrder.total,
                    'invoiceOrderDateCreated': invoiceOrder.dateCreated,
					'totalOrderTaxes': Invoice.findById(params.idInvoice).totalOrderTaxes,
                    'totalInvoiceRetention': invoice.totalInvoiceRetention,
					'total': Invoice.findById(params.idInvoice).totalWithTaxes
            ]}
        }
        else{
            flash.message = message(code: 'invoiceOrder.add.fail')
            redirect(controller: "invoiceorder", action: "list")
        }
    }
	
	def _updateOrder(){
		InvoiceOrder invoiceOrder=InvoiceOrder.findById(params.id)
        Invoice invoice=Invoice.findById(invoiceOrder.invoice.id)

		//actualizamos datos
		invoiceOrder.name=params.name
		invoiceOrder.reference=params.reference
		invoiceOrder.total=params.total
		invoiceOrder.dateCreated=invoiceOrder.dateCreated

		if (invoiceOrder.save(flush: true)){

            invoice.totalOrderTaxes = 0
            invoice.totalWithTaxes = 0
            invoice.totalWithTaxes = 0
            invoice.totalInvoiceRetention = 0
            def totalOrdersNoTaxes = 0

            for (order in InvoiceOrder.findAllByInvoice(invoice)){
                def totalOrder = Double.parseDouble(order.total)
                totalOrdersNoTaxes += totalOrder
                def tax = invoice.tax
                def taxOrder = totalOrder * (tax / 100)

                invoice.totalOrderTaxes = Double.parseDouble(invoice.totalOrderTaxes) + taxOrder
                invoice.totalOrderTaxes = Double.parseDouble(invoice.totalOrderTaxes)
                invoice.totalOrderTaxes = Math.rint(Double.parseDouble(invoice.totalOrderTaxes) * 100)/100;
                invoice.totalWithTaxes = Double.parseDouble(invoice.totalWithTaxes) + totalOrder + taxOrder
                invoice.totalWithTaxes = Math.rint(Double.parseDouble(invoice.totalWithTaxes) * 100)/100;
            }

            def ret = totalOrdersNoTaxes * (invoice.retention / 100)
            def total = Double.parseDouble(invoice.totalWithTaxes) - ret
            if (invoice.totalInvoiceRetention==null){
                invoice.totalInvoiceRetention='0'
            }
            def doubleRetention=Double.parseDouble(invoice.totalInvoiceRetention) + ret
            invoice.totalInvoiceRetention = Math.rint(doubleRetention * 100)/100;
            invoice.totalWithTaxes = Math.rint(total * 100)/100;

			render(contentType: 'text/json') {[
					'success': "OK",
					'id': invoiceOrder.id,
                    'invoiceOrderName': invoiceOrder.name,
					'invoiceOrderReference': invoiceOrder.reference,
                    'invoiceOrderTotal': invoiceOrder.total,
                    'invoiceOrderDateCreated': invoiceOrder.dateCreated,
                    'totalOrderTaxes': invoice.totalOrderTaxes,
                    'totalRetention': invoice.totalInvoiceRetention,
                    'total': invoice.totalWithTaxes
			]}
		}
		else{
			flash.message = message(code: 'invoiceOrder.add.fail')
			redirect(controller: "invoiceorder", action: "list")
		}
	}

    def _removeOrder(){
        InvoiceOrder invoiceOrder=InvoiceOrder.get(params.id)
        Invoice invoice=Invoice.findById(invoiceOrder.invoice.id)

        try {
            invoiceOrder.delete(flush: true)

            invoice.totalOrderTaxes = 0
            invoice.totalWithTaxes = 0
            invoice.totalWithTaxes = 0
            invoice.totalInvoiceRetention = 0
            def totalOrdersNoTaxes = 0

            for (order in InvoiceOrder.findAllByInvoice(invoice)){
                def totalOrder = Double.parseDouble(order.total)
                totalOrdersNoTaxes += totalOrder
                def tax = invoice.tax
                def taxOrder = totalOrder * (tax / 100)

                invoice.totalOrderTaxes = Double.parseDouble(invoice.totalOrderTaxes) + taxOrder
                invoice.totalOrderTaxes = Double.parseDouble(invoice.totalOrderTaxes)
                invoice.totalOrderTaxes = Math.rint(Double.parseDouble(invoice.totalOrderTaxes) * 100)/100;
                invoice.totalWithTaxes = Double.parseDouble(invoice.totalWithTaxes) + totalOrder + taxOrder
                invoice.totalWithTaxes = Math.rint(Double.parseDouble(invoice.totalWithTaxes) * 100)/100;
            }

            if (invoice.tipo==1)
            {
                def ret = totalOrdersNoTaxes * (invoice.retention / 100)
                def total = Double.parseDouble(invoice.totalWithTaxes) - ret
                if (invoice.totalInvoiceRetention==null){
                    invoice.totalInvoiceRetention='0'
                }
                def doubleRetention=Double.parseDouble(invoice.totalInvoiceRetention) + ret
                invoice.totalInvoiceRetention = Math.rint(doubleRetention * 100)/100;
                invoice.totalWithTaxes = Math.rint(total * 100)/100;
            }

            invoice.save(flush: true)

            render(contentType: 'text/json') {[
                    'success': "OK",
                    'id': params.id
            ]}

        }

        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'invoiceOrder.add.fail')
            redirect(controller: "invoiceorder", action: "list")
        }
    }
}

grails-app/views/invoiceorder/_formEditInvoiceOrder.gsp
<g:javascript library="mustache" />
<div class="row-fluid">
    <div class="span12">
        <div id="list-servicio" class="content scaffold-list" role="main">
            <button type="button"
                    id="btnRenderRowOrder"
                    data-button='{"idInvoice": "${invoiceInstance?.id}"}'
                    class="btn btn-success btnAddOrder">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
            <table class="table table-stripped">
                <thead>
                <tr>
                    <g:sortableColumn property="name" title="${message(code: 'invoiceorder.name.label')}" />
                    <g:sortableColumn property="total" title="${message(code: 'invoiceorder.total.label')}" />
                    <td></td>
                    <td></td>
                    
                </tr>
                </thead>
                <tbody id="orders_list">
                <g:each in="${invoiceInstance?.invoiceOrders}" status="i" var="orderInstance">
                    <tr id="orderRowSelected_${orderInstance.id}">
                        <td style="width: 70%;"><div class="col-xs-30"><g:textField name="txtName_${orderInstance.id}" id="txtName_${orderInstance.id}" class="form-control" placeholder=".col-xs-30"
                     		value="${orderInstance?.name}" /></div></td>
                        <td style="width: 20%;"><div class="col-xs-12"><g:textField name="txtTotal_${orderInstance.id}" id="txtTotal_${orderInstance.id}" class="form-control" placeholder=".col-xs-12"
                     		value="${orderInstance?.total}" /></div></td>
                        <td style="width: 5%;">
                        	<button type="button"
                                    data-button='{"id":  ${orderInstance.id}}'
                                    class="btn btn-success btnUpdateOrder">
                                <span class="glyphicon glyphicon-check"></span>
                            </button>
                        </td>
                        <td style="width: 5%;">
                            <button type="button"
                                    data-button='{"id":  ${orderInstance.id}}'
                                    class="btn btn-danger btnRemoveOrder">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </td>
                    </tr>
                </g:each>
                </tbody>
            </table>

        </div> <!-- id=list... -->
    </div> <!-- span12 -->
</div>
<jq:jquery>
    var template;
	var templateFilePath = '<g:resource dir="templates" file="orderInvoice-row.htm" />';

	$.get(templateFilePath, function(templates) {
		template = $(templates);
		//console.log("Plantillas cargadas");
	});

	function renderOrderRow(){
        var buttonData = $.parseJSON($(this).attr('data-button'));
        var t = template.filter('#order-row-available').html();
        $('#orders_list').append(Mustache.render(t, buttonData));
	}

    function addOrder() {
		var buttonData = $.parseJSON($(this).attr('data-button'));
		$.ajax({
			type: "POST",
			url: "${request.contextPath}/invoiceorder/_addOrder",
			dataType: 'json',
			data: {
				idInvoice: buttonData.idInvoice,
				name: $('#txtName__' + buttonData.idInvoice).val(),
				total: $('#txtTotal__' + buttonData.idInvoice).val(),
				retention: $('#retention').val()
			},
			success: function(data) {
				if (data.success == "OK") {
				    $("#orderRowAvailable_" + data.idInvoice).detach();
					var t = template.filter('#order-row-selected').html();
					$('#orders_list').append(Mustache.render(t, data));
					$('#invoiceTaxes').val(data.totalOrderTaxes);
					$('#invoiceRetention').val(data.totalInvoiceRetention);
					$('#invoiceTotal').val(data.total);
				} else {
					if (data.success == "FAIL") {
						helper.showErrors(data.errorMsg, "#axMainMsg");
					}
				}
			},
			error: function(data) {
			    helper.showErrors(data.errorMsg, "#axMainMsg");
			},
			complete: function() {
			}
		});
		return false;
	}
	
	function updateOrder() {
		var buttonData = $.parseJSON($(this).attr('data-button'));
		$.ajax({
			type: "POST",
			url: "${request.contextPath}/invoiceorder/_updateOrder",
			dataType: 'json',
			data: {
				id: buttonData.id,
				name: $('#txtName_' + buttonData.id).val(),
				total: $('#txtTotal_' + buttonData.id).val()
			},
			success: function(data) {
				if (data.success == "OK") {
					alert('Datos guardados.');
					$('#invoiceTaxes').val(data.totalOrderTaxes);
					$('#invoiceRetention').val(data.totalRetention);
					$('#invoiceTotal').val(data.total);

				} else {
					if (data.success == "FAIL") {
						helper.showErrors(data.errorMsg, "#axMainMsg");
					}
				}
			},
			error: function(data) {
			    helper.showErrors(data.errorMsg, "#axMainMsg");
			},
			complete: function() {
			}
		});
		return false;
	}

	function removeOrder() {
	    var buttonData = $.parseJSON($(this).attr('data-button'));
		$.ajax({
			type: "POST",
			url: "${request.contextPath}/invoiceorder/_removeOrder",
			dataType: 'json',
			data: {
				id: buttonData.id
			},
			success: function(data) {
				if (data.success == "OK") {
					$("#orderRowSelected_" + data.id).detach();
				} else {
					if (data.errorMsg) {
						helper.showErrors(data.errorMsg, "#axMainMsg");
					}
				}
			},
			error: function(data) {
			    helper.showErrors(data.errorMsg, "#axMainMsg");
			},
			complete: function() {
			}
		});
		return false;
	}

    $(document).on("click", "#btnRenderRowOrder", renderOrderRow);
    $(document).on("click", ".btnSaveOrder", addOrder);
    $(document).on("click", ".btnRemoveOrder", removeOrder);
    $(document).on("click", ".btnUpdateOrder", updateOrder);
</jq:jquery>